// frontend-vue/src/components/Navbar.vue
<template>
  <header 
    :class="user 
      ? 'bg-slate-900/95 backdrop-blur border-b border-slate-800 text-slate-100' 
      : 'bg-[#F4F1E6]/95 backdrop-blur-md border-b border-[#668A68]/30 text-[#243027]'"
    class="h-16 flex items-center justify-between px-4 lg:px-8 sticky top-0 z-40 transition-colors duration-200"
  >
    <div class="flex items-center gap-4">
      <button 
        v-if="user"
        @click="$emit('toggle-sidebar')" 
        class="lg:hidden p-2 rounded-lg bg-slate-800 text-slate-300 hover:text-white hover:bg-slate-700 focus:outline-none"
        aria-label="Toggle Navigation"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </button>

      <a href="/" class="flex items-center gap-3 group">
        <div class="w-9 h-9 rounded-xl bg-[#31543B] flex items-center justify-center font-black text-[#F4F1E6] text-base shadow-md transition-transform group-hover:scale-105">
          G
        </div>
        <div>
          <div class="text-sm font-bold tracking-tight text-[#243027] flex items-center gap-2">
            GeoField Bio-Logistics
            <span class="text-[10px] uppercase font-bold px-2 py-0.5 rounded-full bg-[#668A68]/15 text-[#31543B] border border-[#668A68]/30 tracking-wider">
              🌿 RUCO Certified
            </span>
          </div>
          <p class="text-[11px] text-[#668A68]">
            National UCO Traceability & Clean Bio-Energy Network
          </p>
        </div>
      </a>
    </div>

    <!-- Right Header Controls -->
    <div class="flex items-center gap-3 sm:gap-4">
      <!-- Network Connectivity Indicator -->
      <div 
        :class="isOnline ? 'bg-[#668A68]/10 border-[#668A68]/30 text-[#31543B]' : 'bg-[#D29A5A]/15 border-[#D29A5A]/40 text-[#243027]'"
        class="flex items-center gap-2 text-xs font-medium px-3 py-1.5 rounded-full border transition-all"
      >
        <span 
          :class="isOnline ? 'bg-[#31543B]' : 'bg-[#D29A5A] animate-pulse'"
          class="w-2 h-2 rounded-full"
        ></span>
        <span class="hidden sm:inline">{{ isOnline ? 'Network Online' : `${offlineCount} Pending Sync` }}</span>
      </div>

      <!-- Authenticated User Menu -->
      <div v-if="user" class="flex items-center gap-3">
        <div class="text-right hidden md:block">
          <div class="text-xs font-bold text-white">{{ user.name }}</div>
          <div class="text-[10px] text-emerald-400 uppercase tracking-wider font-mono">
            {{ userRoleLabel(user.role) }} &bull; {{ user.id }}
          </div>
        </div>
        <button 
          @click="$emit('logout')" 
          class="px-3.5 py-1.5 text-xs font-semibold text-slate-200 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-xl border border-slate-700 hover:border-slate-600 transition shadow"
        >
          Sign Out
        </button>
      </div>

      <!-- Public Sign In / Register Buttons -->
      <div v-else class="flex items-center gap-2.5">
        <button 
          @click="$emit('open-auth', 'login')" 
          class="px-3.5 py-1.5 text-xs font-semibold text-[#31543B] hover:text-[#243027] bg-[#F4F1E6] hover:bg-[#EAE6D8] rounded-xl border border-[#668A68]/40 transition shadow-xs cursor-pointer"
        >
          Sign In
        </button>
        <button 
          @click="$emit('open-auth', 'register')" 
          class="px-4 py-1.5 text-xs font-bold text-[#F4F1E6] bg-[#31543B] hover:bg-[#243027] rounded-xl shadow-lg transition cursor-pointer"
        >
          Register FBO
        </button>
      </div>
    </div>
  </header>
</template>

<script setup>
defineProps({
  user: Object,
  isOnline: Boolean,
  offlineCount: Number,
});
defineEmits(['toggle-sidebar', 'logout', 'open-auth']);

function userRoleLabel(role) {
  if (role === 'admin') return 'Super Admin';
  if (role === 'agent') return 'Field Executive';
  if (role === 'seller') return 'Food Business Operator';
  return role;
}
</script>

// frontend/src/components/Navbar.tsx
"use client";

import React, { useState } from "react";
import { Leaf, ArrowRight, ShieldCheck, Menu, X } from "lucide-react";

interface NavbarProps {
  onSignIn?: () => void;
  onRegister?: () => void;
}

export default function Navbar({ onSignIn, onRegister }: NavbarProps) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <header className="sticky top-0 z-50 w-full bg-cream/90 backdrop-blur-md border-b border-olive/20 transition-all">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
        {/* Brand Group */}
        <div className="flex items-center gap-4">
          {/* Logo Mark: Green square with clean geometric G */}
          <div className="w-10 h-10 rounded-lg bg-forest flex items-center justify-center shadow-md shadow-forest/20 text-cream font-black text-xl tracking-tighter transition-transform hover:scale-105 select-none">
            G
          </div>

          {/* Brand Name + Tagline Stacked */}
          <div className="flex flex-col">
            <div className="flex items-center gap-2">
              <span className="font-extrabold text-lg sm:text-xl tracking-tight text-nearblack">
                GeoField
              </span>
              <span className="text-xs uppercase font-mono tracking-widest text-olive font-bold px-1.5 py-0.5 rounded bg-olive/10 border border-olive/20">
                Bio-Logistics
              </span>
            </div>
            <span className="text-[11px] text-nearblack/60 tracking-tight font-medium hidden sm:block">
              National UCO Traceability &amp; Clean Bio-Energy Network
            </span>
          </div>
        </div>

        {/* Center / Secondary Trust & Live Status */}
        <div className="hidden lg:flex items-center gap-3">
          {/* Trust Badge: RUCO CERTIFIED */}
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-olive/10 border border-olive/30 text-olive text-xs font-semibold">
            <Leaf className="w-3.5 h-3.5 text-olive" />
            <span className="hud-label tracking-wider">RUCO CERTIFIED</span>
          </div>

          {/* Live Status Pill: Network Online */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-forest/5 border border-forest/15 text-nearblack text-xs font-mono">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-olive opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-olive"></span>
            </span>
            <span className="text-[11px] font-semibold tracking-wider uppercase text-nearblack/80">
              Network Online · 284 FBOs Live
            </span>
          </div>
        </div>

        {/* Right Action Group */}
        <div className="flex items-center gap-3">
          {/* Ghost Sign In Button */}
          <button
            onClick={onSignIn}
            className="hidden sm:inline-flex items-center px-4 py-2 text-xs font-bold text-nearblack hover:text-forest transition-colors rounded-xl hover:bg-forest/5 border border-transparent hover:border-forest/20"
          >
            Sign In
          </button>

          {/* Solid CTA: Register FBO */}
          <button
            onClick={onRegister}
            className="group relative inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-forest text-cream font-bold text-xs sm:text-sm shadow-md hover:shadow-lg hover:shadow-forest/20 transition-all duration-300 hover:-translate-y-0.5 active:translate-y-0"
          >
            <ShieldCheck className="w-4 h-4 text-amber" />
            <span>Register FBO</span>
            <ArrowRight className="w-3.5 h-3.5 text-cream/70 group-hover:translate-x-1 transition-transform" />
          </button>

          {/* Mobile Menu Toggle */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="sm:hidden p-2 text-nearblack hover:text-forest focus:outline-none"
            aria-label="Toggle menu"
          >
            {mobileMenuOpen ? (
              <X className="w-6 h-6" />
            ) : (
              <Menu className="w-6 h-6" />
            )}
          </button>
        </div>
      </div>

      {/* Mobile Drawer */}
      {mobileMenuOpen && (
        <div className="sm:hidden px-4 pt-2 pb-6 bg-cream border-b border-olive/20 space-y-3">
          <div className="flex items-center justify-between py-2 border-b border-olive/10 text-xs">
            <span className="inline-flex items-center gap-1.5 text-olive font-semibold">
              <Leaf className="w-3.5 h-3.5" /> RUCO CERTIFIED
            </span>
            <span className="font-mono text-nearblack/70 flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-olive animate-pulse"></span>
              Network Online
            </span>
          </div>
          <button
            onClick={() => {
              setMobileMenuOpen(false);
              onSignIn?.();
            }}
            className="w-full py-2.5 text-xs font-bold text-center text-nearblack bg-cream-200/60 rounded-xl"
          >
            Sign In to Portal
          </button>
        </div>
      )}
    </header>
  );
}
